---
# file roles/shiny/tasks/install_shiny.yml
- name: Installing shiny R packages on "{{ hostname }}"
  become: true
  shell: R -e "install.packages('shiny', repos='http://cran.rstudio.com/')" && mkdir -p /root/status && touch /root/status/shinyR
  args:
          creates: /root/status/shinyR
- name:  Installing gdebi for debian package installation on "{{ hostname }}"
  become: true
  apt:
          name: gdebi-core
- name: Download shiny server on "{{ hostname }}"
  become: true
  shell: wget https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.9.923-amd64.deb
  args:
          chdir: /root/status
          creates: /root/status/shiny-server-1.5.9.923-amd64.deb
- name: Install shiny server
  become: true
  shell: gdebi -n shiny-server-1.5.9.923-amd64.deb
  args:
          chdir: /root/status
          creates: /opt/shiny-server
  notify: Install custom shiny apps
