---
# file roles/autofs_services/tasks/configure_autofs.yml
- name: Copy automaster to "{{ hostname }}"
  become: true
  copy:
          src: "{{ item }}.{{ hostname }}"
          dest: "/etc/{{ item }}"
          mode: 0644
          owner: root
          group: root
  loop: "{{ autofs_files }}"
  notify: Restart autofs
