---
# file roles/slurmd/tasks/slurmd.yml
- name: Install slurmd package on "{{ hostname }}"
  become: true
  apt:
          name: slurmd
- name: Create slurmd spool directory on "{{ hostname }}"
  become: true
  file:
          path: /var/spool/slurmd
          state: directory
          owner: slurm
          group: slurm
- name: Create slurm.conf file on "{{ hostname }}"
  become: true
  template:
          src: slurm.conf.tpl
          dest: /etc/slurm-llnl/slurm.conf
  notify: Restart slurmd
